### ISSUE TITLE
HTML Elements Code-Along

### ISSUE THREAD

**Issue by MysticRiver** [learn-co-curriculum/html-css-how-the-web-works#1]
The Git commands in the lesson HTML Elements Code-Along are all wrong.
I made the required HTML changes but following along in the tutorial up to the gitcommands do not result in my branch being merged or my github pull request being done.
I have repeated this several times and the result is still the same.
Can someone test this by doing the lesson and see if they get the same result?
I'm unsable to proceed to the next lesson as a result of this.
Please help.

**Comment by AnnJohn** [comment]
hi @MysticRiver sorry for the issue that you're having. We'll look at this right away. Thanks!

**Comment by pletcher** [comment]
Looks like you found a way through! Closed via https://github.com/learn-co-curriculum/html-css-html-elements-code-along/pull/3

**Comment by pletcher** [comment]
(Thanks for raising this issue, and for submitting those PRs.)
