### ISSUE TITLE
Learn IDE Authenticated on Multiple Devices

### ISSUE THREAD

**Issue by MysticRiver** [learn-co-curriculum/html-css-how-the-web-works#3]
Is it possible to use the Learn IDE on more than one device?
Some people have multiple devices like a laptop and a desktop or a home computer and a work computer. So It would be great if You could use the Learn IDE on multiple devices. Or perhaps make it entirely cloudbased without the need of a download.

**Comment by AnnJohn** [comment]
hi @MysticRiver as of now, it's not possible to use the Learn IDE on multiple devices which I believe might be mentioned during the onboarding process. 

We definitely know that that is a pain point and will be working on making this possible soon.
